
pool:
  vmImage: ubuntu-latest

steps:
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false


    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'Sonarcloud'
        organization: 'rodrigorubilark'
        projectKey: 'RodrigoRubilarK_pet-clinic'
        projectName: 'pet-clinic'


        - task: Gradle@3
          inputs:
            gradleWrapperFile: 'gradlew'
            tasks: 'build'
            publishJUnitResults: true
            testResultsFiles: '**/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            sonarQubeRunAnalysis: true
            sqGradlePluginVersionChoice: 'specify'
            sonarQubeGradlePluginVersion: '2.6.1'
            spotBugsAnalysis: false